accreditation/accreditation/urls.py
from django.conf.urls import url
from django.contrib import admin
from accreditation_app import views as accreditation_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', accreditation_views.accreditation_page, name='accreditation_page'),
    url(
        r'^terms-conditions/', accreditation_views.terms_conditons_page, name='terms_conditons_page'
    ),
]

accreditation/accreditation_app/urls.py
from django.conf.urls import url
from accreditation_app import views


urlpatterns = [
]

accreditation/accreditation_app/models.py
from django.core.exceptions import ValidationError
from django.db import models
from postmark.core import PMMail, PMMailSendException

from accreditation.settings import (
    ACCREDITATION_CHOICE_PHOTO,
    ACCREDITATION_CHOICE_JOURNALIST,
    ACCREDITATION_CHOICE_FESTIVAl,
    PHOTO_A,
    PHOTO_B,
    PHOTO_C,
    POSTMARK_APPLICATION_DECLINE_TEMPLATE,
    POSTMARK_APPLICATION_DISCOUNT_TEMPLATE,
    POSTMARK_APPLICATION_GRANT_TEMPLATE,
    POSTMARK_SENDER,
)


def send_email(data, template_id=POSTMARK_APPLICATION_DECLINE_TEMPLATE, sender=POSTMARK_SENDER):
    pm = PMMail(
        to=data['email'],
        sender=POSTMARK_SENDER,
        template_id=template_id,
        template_model=data
    )
    pm.send()


class AccreditatonApplication(models.Model):
    TYPE_OF_ACCREDITATION_CHOICES = (
        (ACCREDITATION_CHOICE_PHOTO, 'Photo Pass'),
        (ACCREDITATION_CHOICE_JOURNALIST, 'Journalist Pass'),
        (ACCREDITATION_CHOICE_FESTIVAl, 'Festival Pass'),
    )
    TYPE_OF_PHOTO_CHOICES = (
        (PHOTO_A, 'Photo Pass A'),
        (PHOTO_B, 'Photo Pass B'),
        (PHOTO_C, 'Photo Pass C'),
    )

    first_name = models.CharField(null=False, blank=False, max_length=50, default='')
    last_name = models.CharField(null=False, blank=False, max_length=50, default='')
    email = models.EmailField(null=False, blank=False, default='')
    granted = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)
    application = models.TextField(null=False, blank=False, default=None)
    applied = models.DateTimeField(auto_now_add=True)
    discount_amount = models.IntegerField(null=True, blank=True, default=None)
    discount_code = models.CharField(null=True, blank=True, max_length=50, default=None)
    type_of_accreditation = models.CharField(
        null=False,
        blank=False,
        max_length=9,
        choices=TYPE_OF_ACCREDITATION_CHOICES,
        default=None,
    )
    photo_type = models.CharField(
        null=True,
        blank=True,
        max_length=1,
        choices=TYPE_OF_PHOTO_CHOICES,
        default=None,
    )

    def __str__(self):
        return "{} {} {}".format(self.first_name, self.last_name, self.email)

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        data = {
            'first_name': self.first_name,
            'last_name': self.last_name,
            'email': self.email,
        }
        if self.granted and self.declined:
            raise ValidationError("Granted and declined are mutually exclusive.")
        if self.granted:
            template_id = POSTMARK_APPLICATION_GRANT_TEMPLATE
            if self.discount_amount and self.discount_code:
                data['discount_amount'] = self.discount_amount
                data['discount_code'] = self.discount_code
                template_id = POSTMARK_APPLICATION_DISCOUNT_TEMPLATE
            try:
                send_email(
                    data,
                    template_id,
                    POSTMARK_SENDER,
                )
                super(AccreditatonApplication, self).save(*args, **kwargs)
            except PMMailSendException:
                raise Exception
        elif self.declined:
            try:
                send_email(
                    data,
                    POSTMARK_APPLICATION_DECLINE_TEMPLATE,
                    POSTMARK_SENDER,
                )
                super(AccreditatonApplication, self).save(*args, **kwargs)
            except PMMailSendException:
                raise Exception
        else:
            super(AccreditatonApplication, self).save(*args, **kwargs)

accreditation/accreditation_app/views.py
from accreditation_app.models import AccreditatonApplication
from django.core.exceptions import ValidationError
from django.shortcuts import render
from postmark.core import PMMail, PMMailSendException

from accreditation.settings import (
    POSTMARK_APPLICATION_SENT_TEMPLATE,
    POSTMARK_SENDER,
)


def accreditation_page(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        type_of_accreditation = request.POST['type_of_accreditation']
        application_text = request.POST['application']

        application = AccreditatonApplication.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            type_of_accreditation=type_of_accreditation,
            application=application_text
        )
        try:
            application.full_clean()
            data = {
                'first_name': first_name,
                'last_name': last_name,
                'email': email,
            }
            pm = PMMail(
                to=email,
                sender=POSTMARK_SENDER,
                template_id=POSTMARK_APPLICATION_SENT_TEMPLATE,
                template_model=data
            )
            pm.send()
        except ValidationError as e:
            application.delete()
            data = {
                'error': e
            }
        except PMMailSendException as e:
            application.delete()
            data = {
                'error': e
            }
        data['application'] = application_text
        data['type_of_accreditation'] = type_of_accreditation
        return render(request, 'application_accepted.html', data)
    else:
        return render(request, 'accreditation.html')


def terms_conditons_page(request):
    return render(request, 'terms_conditons.html')

accreditation/accreditation_app/templates/accreditation.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Popaganda Accreditation</title>
    <link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>

    <body>
        <div class="container">
            <h1>Apply for Popaganda Accreditation</h1>

            <form action="/" method="POST">
                <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    <input id="id_first_name" class="form-control" name="first_name" placeholder="First Name" required/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input id="id_last_name" class="form-control" name="last_name" placeholder="Last Name" required/>
                </div>
                <div class="form-group">
                    <label for="type_of_accreditation">Type of accreditation</label>
                    <select class="form-control" id="type_of_accreditation" name="type_of_accreditation" required>
                        <option id="empty" value="" selected></option>
                        <option id="photo" value="photo">Photo Pass</option>
                        <option id="festival" value="festival">Festival Pass</option>
                        <option id="jounalist" value="jounalist">Journalist Pass</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_application">Application Text</label>
                    <textarea id="id_application" class="form-control" rows="3" name="application" placeholder="Futher information" required/></textarea>
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    <input id="id_email" type="email" class="form-control" name="email" placeholder="Email" required/>
                </div>
                <div class="form-check">
                    <input id="id_terms" type="checkbox" class="form-check-input" name="terms" required>
                    <label class="form-check-label" for="id_terms"> I agree to  <a href="/terms-conditions/">Terms and Conditions</a> </label>
                </div>
                <button id='send_button' type="submit" class="btn btn-primary">Submit</button>
                {% csrf_token %}
            </form>
        </div>
    </body>
</html>

accreditation/accreditation_app/templates/application_accepted.html
<html>
    <head>
        <title>Application Accepted</title>
    </head>
    <body>
        {% if error %}
          <div class="form-group has-error">
            <p>Your application was not sent due to the following errors:</p>
            <p>{{ error }}</p>
          </div>
        {% else %}
        <div id='id_user_info'>
            <h1>Your application has been accepted</h1>
            <p>{{ first_name }} {{ last_name }} an email with further information was sent to {{ email }}.</p>
            <p>You applied for: {{ type_of_accreditation }}</p>
            <p>Your application: {{ application }}</p>
        </div>
        {% endif %}
    </body>
</html>

accreditation/accreditation_app/templates/terms_conditons.html
<html>
    <head>
        <title>Terms and Conditions</title>
    </head>
    <body>
        <h1>Terms and Conditions</h1>
        By approving... bla bla bla...
    </body>
</html>